from .saxtypes import ComplexArray

__all__ = ["huber_loss", "l2_reg", "mse"]

def mse(x: ComplexArray, y: ComplexArray) -> float: ...
def huber_loss(x: ComplexArray, y: ComplexArray, delta: float = 0.5) -> float: ...
def l2_reg(weights: dict[str, ComplexArray]) -> float: ...
