from typing import overload

import sax

__all__ = ["multimode", "singlemode"]

@overload
def multimode(S: sax.SDictModel, modes: tuple[str, ...] = ...) -> sax.SDictModel: ...
@overload
def multimode(S: sax.SCooModel, modes: tuple[str, ...] = ...) -> sax.SCooModel: ...
@overload
def multimode(S: sax.SDenseModel, modes: tuple[str, ...] = ...) -> sax.SDenseModel: ...
@overload
def multimode(S: sax.SDict, modes: tuple[str, ...] = ...) -> sax.SDictMM: ...
@overload
def multimode(S: sax.SCoo, modes: tuple[str, ...] = ...) -> sax.SCooMM: ...
@overload
def multimode(S: sax.SDense, modes: tuple[str, ...] = ...) -> sax.SDenseMM: ...
@overload
def singlemode(S: sax.SDictModel, mode: str = ...) -> sax.SDictModelSM: ...
@overload
def singlemode(S: sax.SCooModel, mode: str = ...) -> sax.SCooModelSM: ...
@overload
def singlemode(S: sax.SDenseModel, mode: str = ...) -> sax.SDenseModelSM: ...
@overload
def singlemode(S: sax.SDict, mode: str = ...) -> sax.SDictSM: ...
@overload
def singlemode(S: sax.SCoo, mode: str = ...) -> sax.SCooSM: ...
@overload
def singlemode(S: sax.SDense, mode: str = ...) -> sax.SDenseSM: ...
